const BASE='https://hackathon.api.qloo.com';
export class AppError extends Error {constructor(status,code,message){super(message);this.status=status;this.code=code}}
function entities(data){if(Array.isArray(data?.results?.entities))return data.results.entities;if(Array.isArray(data?.entities))return data.entities;if(Array.isArray(data?.results))return data.results;throw new AppError(502,'RESPONSE_FORMAT','Qloo returned an unexpected response. Please try again later.');}
const normalize=s=>s.normalize('NFKC').trim().toLocaleLowerCase('en');
const movieType=e=>e?.type==='urn:entity:movie'||(Array.isArray(e?.types)&&e.types.includes('urn:entity:movie'));
export function validateTitles(input){if(!input||!Array.isArray(input.titles)||input.titles.length<1||input.titles.length>5||input.titles.some(t=>typeof t!=='string'||!t.trim()||t.length>120))throw new AppError(400,'INVALID_INPUT','Enter between one and five movie titles, up to 120 characters each.');return [...new Set(input.titles.map(t=>t.trim()))];}
export async function recommend(input,{apiKey,fetchImpl=fetch,signal}={}){
 const titles=validateTitles(input);if(!apiKey?.trim())throw new AppError(503,'KEY_PENDING','Live recommendations are not connected yet. You can explore sample picks instead.');
 const timeout=AbortSignal.timeout(25000),combined=signal?AbortSignal.any([signal,timeout]):timeout;
 async function get(path,params){const url=new URL(path,BASE);url.search=new URLSearchParams(params).toString();let response;try{response=await fetchImpl(url,{headers:{'X-Api-Key':apiKey,Accept:'application/json'},signal:combined,redirect:'error'});}catch{throw new AppError(504,'UPSTREAM_UNAVAILABLE','Qloo could not be reached in time. Please try again.');}if(!response.ok){if([401,403].includes(response.status))throw new AppError(502,'QLOO_ACCESS','Qloo access needs attention. Please try sample picks for now.');if(response.status===429)throw new AppError(429,'QLOO_LIMIT','Qloo is busy or its request limit has been reached. Please try again later.');throw new AppError(502,'QLOO_ERROR','Qloo could not complete this request. Please try again.');}try{return await response.json();}catch{throw new AppError(502,'RESPONSE_FORMAT','Qloo returned an unreadable response. Please try again later.');}}
 const matched=[];
 // Do not assume that the first search result is the intended movie.
 for(const title of titles){const found=entities(await get('/search',{query:title,take:'10'})).filter(e=>movieType(e)&&typeof e.name==='string'&&typeof e.entity_id==='string');const exact=found.filter(e=>normalize(e.name)===normalize(title));if(exact.length!==1)throw new AppError(422,exact.length?'AMBIGUOUS_TITLE':'TITLE_NOT_FOUND',exact.length?`More than one movie is named “${title}”. Try a different favourite for now.`:`We could not identify “${title}” confidently. Check the title or try another movie.`);matched.push(exact[0]);}
 const ids=[...new Set(matched.map(e=>e.entity_id))];const data=await get('/v2/insights',{'filter.type':'urn:entity:movie','signal.interests.entities':ids.join(','),take:'10'});
 const seen=new Set(ids);const movies=entities(data).filter(e=>typeof e?.entity_id==='string'&&typeof e?.name==='string'&&!seen.has(e.entity_id)&&seen.add(e.entity_id)).map(e=>({id:e.entity_id,title:e.name,year:e.properties?.release_year??null,minutes:null,genre:'',note:typeof e.properties?.description==='string'?e.properties.description:'Recommended by Qloo from your selected movies.'}));
 return {mode:'live',matched:matched.map(e=>({id:e.entity_id,title:e.name})),movies,notice:'Qloo recommendations use your favourite movies. Mood matching and conversational refinement are not connected yet.'};
}
